name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Install dependencies
      run: bundle install
    - name: Run linter
      run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ['3.2', '3.3']
        rails_version: [7.0.8]

    name: Test GeoBlacklight / Ruby ${{ matrix.ruby_version }} / Rails ${{ matrix.rails_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Create Solr container
        run: docker run -d -p 8983:8983 geoblacklight/solr:8.9-v1.0.0 server/scripts/ci-start.sh
      - name: Install dependencies
        run: bundle install
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
          LIGHT: geoblacklight
      - name: Setup Yarn
        run: exec "yarnpkg"
      - name: Load config into solr
        run: |
            cd solr/geoblacklight/conf
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://solr:SolrRocks@127.0.0.1:8983/solr/admin/configs?action=UPLOAD&name=blacklight"
            curl -H 'Content-type: application/json' http://solr:SolrRocks@127.0.0.1:8983/api/collections/  -d '{create: {name: blacklight-core, config: blacklight, numShards: 1}}'
      - name: Run tests
        run: bundle exec rake ci
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
          ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test'
          SOLR_URL: http://solr:SolrRocks@localhost:8983/solr/blacklight-core
          LIGHT: geoblacklight